name: Update Changelog

on:
  push:
    branches: ["master", "main"]
  pull_request:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      - name: Set git details
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "action@github.com"
      - name: Update changelog
        run: uv run --frozen scripts/update_changelog.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}